### ISSUE TITLE
Problem with https://bit.dev/mui-org/material-ui/fade

### ISSUE THREAD

**Issue by howardkitto** [stecrv/polluters#1]
Hi Stefan

We can't instal the app. Something is wrong with this package.

https://bit.dev/mui-org/material-ui/fade

Thanks

Howard

**Comment by howardkitto** [comment]
ah we found the fix...

npm config set @bit:registry https://node.bit.dev/

**Comment by stecrv** [comment]
added to readme, @howardkitto  can I close this ticket?
